version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      - MAVEN_OPTS: -Xmx1024m
    steps:
      - checkout
      - restore_cache:
          keys:
          - deps-{{ checksum "pom.xml" }}
          - deps-
      - run: cd juint/ && mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: deps-{{ checksum "pom.xml" }}
      - run: mvn integration-test
